/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-05-28 05:35:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Employee Salary Management System</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        html, body {\r\n");
      out.write("            margin: 0; \r\n");
      out.write("            padding: 0; \r\n");
      out.write("            height: 100%;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("             background-color: lightblue;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            width: 100vw;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: flex-start;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("            color: #333;\r\n");
      out.write("            padding: 30px 40px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 90vw;\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header h1 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header p {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: #5d6d7e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header .info {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            color: #34495e;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-container {\r\n");
      out.write("            width: 90vw;\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-row {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 40px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            flex-wrap: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-card {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 6px 20px rgba(0,0,0,0.15);\r\n");
      out.write("            width: 220px;\r\n");
      out.write("            height: 140px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #2980b9;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("            border: 2px solid transparent;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-card:hover {\r\n");
      out.write("            transform: translateY(-8px);\r\n");
      out.write("            box-shadow: 0 12px 30px rgba(0,0,0,0.25);\r\n");
      out.write("            background: rgba(255, 255, 255, 1);\r\n");
      out.write("            border-color: #3498db;\r\n");
      out.write("            color: #1f4e79;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loading-overlay {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0; \r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%; \r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.6);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .loading-content {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 30px 40px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .spinner {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border: 4px solid #ecf0f1;\r\n");
      out.write("            border-top: 4px solid #3498db;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            animation: spin 1s linear infinite;\r\n");
      out.write("            margin: 0 auto 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes spin {\r\n");
      out.write("            to { transform: rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 720px) {\r\n");
      out.write("            .nav-row {\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                gap: 20px;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .nav-card {\r\n");
      out.write("                width: 45vw;\r\n");
      out.write("                max-width: 220px;\r\n");
      out.write("                height: 120px;\r\n");
      out.write("                font-size: 1.1rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    // Current date formatting
    Date now = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE, MMMM dd, yyyy");
    String currentDate = sdf.format(now);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <h1>Employee Salary Management System</h1>\r\n");
      out.write("    <p>Manage employee records, update details, and generate reports easily</p>\r\n");
      out.write("    <div class=\"info\">Date: <strong>");
      out.print( currentDate );
      out.write("</strong></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"nav-container\">\r\n");
      out.write("    <!-- First row: Add, Update, Delete -->\r\n");
      out.write("    <div class=\"nav-row\">\r\n");
      out.write("        <a href=\"empadd.jsp\" class=\"nav-card\">Add Employee</a>\r\n");
      out.write("        <a href=\"empupdate.jsp\" class=\"nav-card\">Update Employee</a>\r\n");
      out.write("        <a href=\"empdelete.jsp\" class=\"nav-card\">Delete Employee</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Second row: View, Reports -->\r\n");
      out.write("    <div class=\"nav-row\" style=\"max-width: 480px; justify-content: space-evenly;\">\r\n");
      out.write("        <a href=\"empdisplay.jsp\" class=\"nav-card\">View Employees</a>\r\n");
      out.write("        <a href=\"reports.jsp\" class=\"nav-card\">Reports</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Loading overlay -->\r\n");
      out.write("<div class=\"loading-overlay\" id=\"loadingOverlay\">\r\n");
      out.write("    <div class=\"loading-content\">\r\n");
      out.write("        <div class=\"spinner\"></div>\r\n");
      out.write("        <p>Loading, please wait...</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Show loading overlay on nav-card click\r\n");
      out.write("    document.querySelectorAll('.nav-card').forEach(card => {\r\n");
      out.write("        card.addEventListener('click', () => {\r\n");
      out.write("            document.getElementById('loadingOverlay').style.display = 'flex';\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
