/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-05-30 14:52:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.model.Employee;

public final class report_005fresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.Employee");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String action = request.getParameter("action");
List<Employee> employees = (List<Employee>) session.getAttribute("filteredEmployees");

if (employees == null) {
out.println("<h3>No data found. Please generate a report first.</h3>");
return;
}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Report Results</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background-color: lightblue;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            font-size: 2.2rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border-bottom: 3px solid #3498db;\r\n");
      out.write("            padding-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        p {\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #34495e;\r\n");
      out.write("            background-color: #ecf0f1;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border-left: 4px solid #3498db;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            margin: 30px 0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        th {\r\n");
      out.write("            background: linear-gradient(135deg, #3498db, #2980b9);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 18px 15px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        td {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-bottom: 1px solid #ecf0f1;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        tr:nth-child(even) {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        tr:hover {\r\n");
      out.write("            background-color: #e3f2fd;\r\n");
      out.write("            transform: scale(1.01);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button-container {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            padding-top: 30px;\r\n");
      out.write("            border-top: 1px solid #ecf0f1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-button {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 16px 32px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(102, 126, 234, 0.3);\r\n");
      out.write("            transition: all 0.4s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-button::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: left 0.6s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-button:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-button:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #5a67d8 0%, #667eea 100%);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 12px 35px rgba(102, 126, 234, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-button:active {\r\n");
      out.write("            transform: translateY(-1px);\r\n");
      out.write("            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button-icon {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-button:hover .button-icon {\r\n");
      out.write("            transform: translateX(-3px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button-text {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            body {\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 25px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            h2 {\r\n");
      out.write("                font-size: 1.8rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            table {\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            th, td {\r\n");
      out.write("                padding: 12px 8px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        .back-link {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 8px 12px;\r\n");
      out.write("    background-color: #f0f0f0;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    transition: background-color 0.3s, color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back-link:hover {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2>Report Results</h2>\r\n");
      out.write("\r\n");
      out.write("    <p>Filter Type: <b>");
      out.print( action );
      out.write("</b></p>\r\n");
      out.write("\r\n");
      out.write("    <table border=\"1\" cellpadding=\"10\" cellspacing=\"0\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Emp No</th>\r\n");
      out.write("<th>Name</th>\r\n");
      out.write("<th>Date of Joining</th>\r\n");
      out.write("<th>Gender</th>\r\n");
      out.write("<th>Salary</th>\r\n");
      out.write("</tr>\r\n");

for(Employee e : employees) {

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print( e.getId() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( e.getName() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( e.getDoj() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( e.getGender() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print( e.getSalary() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<a href=\"report_form.jsp?action=");
      out.print(action);
      out.write("\" class=\"back-link\">&#8592; Back to Filter</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
